name: cfstep-helmfile
title: Release using Helmfile
image: codefresh/cfstep-helmfile:0.90.2
tag: 0.0.1
version: 0.0.1
description: Release using Helmfile
categories:
- featured
- deployment
keywords:
- helm
- helmfile
sources:
- https://github.com/codefresh-contrib/cfstep-helmfile
maintainers:
- name: Dustin Van Buskirk
  email: dustinvb@codefresh.io
icon: https://raw.githubusercontent.com/codefresh-plugins/cfstep-helm/master/icon.jpg
envs:
- name: KUBE_CONTEXT
  type: required
  description: Kubernetes context to use (the name of the cluster as configured in
    Codefresh) (required)
- name: CHART_NAME
  type: required
  description: Helm chart name to release (path to chart folder, or name of packaged
    chart) (required)
- name: RELEASE_NAME
  type: required
  description: Helm release name
- name: NAMESPACE
  type: optional
  description: target Kubernetes namespace
- name: TILLER_NAMESPACE
  type: optional
  description: Kubernetes namespace where tiller is at
- name: CHART_VERSION
  type: optional
  description: application chart version to install
- name: CHART_REPO_URL
  type: optional
  description: Helm chart repository URL (overriden by injected Helm repository context)
- name: CUSTOMFILE_<name>
  type: optional
  description: Values file to provide to Helm (as --file). see usage information below.
- name: CUSTOM_<name>
  type: optional
  description: Value to provide to Helm (as --set). see usage information below.
